// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1lHsUEwQcO7sFDRc-kjDvdR-2jqZ-FdU',
    appId: '1:835093936280:web:636c7ee9d46a4f711278ed',
    messagingSenderId: '835093936280',
    projectId: 'sipadu-halteng',
    authDomain: 'sipadu-halteng.firebaseapp.com',
    storageBucket: 'sipadu-halteng.appspot.com',
    measurementId: 'G-D4CSEHGEJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrt7FWJI4aRhABd-cy2Cy_UDa5B7Mg9fU',
    appId: '1:835093936280:android:f70754b059471d671278ed',
    messagingSenderId: '835093936280',
    projectId: 'sipadu-halteng',
    storageBucket: 'sipadu-halteng.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKF7BV7baxEiiMZvaW9ZhxNjt4tdPg8xo',
    appId: '1:835093936280:ios:a091680d2f73057c1278ed',
    messagingSenderId: '835093936280',
    projectId: 'sipadu-halteng',
    storageBucket: 'sipadu-halteng.appspot.com',
    iosClientId: '835093936280-54ngmkn303166rp1odmdor1ealo7cu03.apps.googleusercontent.com',
    iosBundleId: 'com.example.sipadu8202',
  );
}
